#!/bin/bash

## Shell Opts ----------------------------------------------------------------

set -euv
set -o pipefail

## Vars ----------------------------------------------------------------------

# These vars are set by the CI environment, but are given defaults
# here to cater for situations where someone is executing the test
# outside of the CI environment.
export RE_HOOK_ARTIFACT_DIR="${RE_HOOK_ARTIFACT_DIR:-/tmp/artifacts}"
export RE_HOOK_RESULT_DIR="${RE_HOOK_RESULT_DIR:-/tmp/results}"

## Functions -----------------------------------------------------------------
export BASE_DIR=${BASE_DIR:-"/opt/rpc-openstack"}
source ${BASE_DIR}/scripts/functions.sh

## Main ----------------------------------------------------------------------

echo "#### BEGIN LOG COLLECTION ###"

collect_logs_cmd="ansible-playbook"
collect_logs_cmd+=" --ssh-common-args='-o StrictHostKeyChecking=no'"
collect_logs_cmd+=" --extra-vars='artifacts_dir=${RE_HOOK_ARTIFACT_DIR}'"
collect_logs_cmd+=" --extra-vars='result_dir=${RE_HOOK_RESULT_DIR}'"

if [[ $RE_JOB_IMAGE =~ .*mnaio.* ]]; then
  collect_logs_cmd+=" --extra-vars='target_hosts=pxe_servers'"
  collect_logs_cmd+=" --inventory='/opt/openstack-ansible-ops/multi-node-aio/playbooks/inventory/hosts'"
else
  collect_logs_cmd+=" --extra-vars='target_hosts=localhost'"
fi

collect_logs_cmd+=" $(dirname ${0})/collect_logs.yml"

eval $collect_logs_cmd || true

echo "#### END LOG COLLECTION ###"

extract_rpc_release(){
  awk '/rpc_release/{print $2}' | tr -d '"'
}
