---

- hosts: localhost
  gather_facts: "{{ gather_facts | default(false) }}"
  tasks:
    - name: Find overrides file
      stat:
        path: "/etc/openstack_deploy/{{ item }}"
        follow: yes
      changed_when: false
      register: _osa_config
      until: _osa_config | success
      with_items:
        - 'user_local_variables.yml'
        - 'user_osa_variables_overrides.yml'
        - 'user_variables.yml'

    - name: Set osa config
      set_fact:
        osa_config: "/etc/openstack_deploy/{{ _osa_config.results[0].item }}"

    - name: Gather ceph client variables
      include_vars: "{{ item }}"
      vars:
        ceph_client_role_dir: "/etc/ansible/roles/ceph_client/vars"
      with_first_found:
        - "{{ ceph_client_role_dir }}/{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ceph_client_role_dir }}/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ceph_client_role_dir }}/{{ ansible_distribution | lower }}.{{ ansible_distribution_version | lower }}.yml"
        - "{{ ceph_client_role_dir }}/{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ceph_client_role_dir }}/{{ ansible_distribution | lower }}.yml"
        - "{{ ceph_client_role_dir }}/{{ ansible_os_family | lower }}.yml"

    - name: Adding required variables
      lineinfile:
        dest: "{{ osa_config }}"
        line: "{{ item.key }}: {{ item.value }}"
        regexp: "{{ item.regexp | default('^' + item.key) }}"
      with_items:
          # Freeze ceph_stable_release prior openstack upgrade to prevent accidental ceph client changes
          - key: "ceph_stable_release"
            value: "{{ ceph_stable_release | default('nautilus') }}"
          - key: "upgrade_ceph_packages"
            value: False
      when: osa_config |length > 26

    - name: Locate python_ceph_packages variable
      shell:
        egrep '^python_ceph_packages:.*' "{{ osa_config }}" | wc -l || true
      register: _python_ceph_packages_override
      when: osa_config |length > 26

    - name: Adding python_ceph_packages variable
      shell: |
        cat << EOT >> {{ osa_config }}
        python_ceph_packages:
        {{ python_ceph_packages | to_nice_yaml(indent=4) }}
        EOT
      when:
        - _python_ceph_packages_override is defined
        - _python_ceph_packages_override.stdout == "0"
