---
# Copyright 2018, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Confirm wsrep_cluster_size is equal to the amount of galera containers
  shell: "mysql -e \"show status like 'wsrep_cluster_size'\" | grep wsrep_cluster_size | awk '{print $2}'"
  register: wsrep_cluster_size
  delegate_to: "{{ groups['galera_all'][0] }}"
  ignore_errors: yes

- name: Display wsrep_cluster_size
  debug:
    var: wsrep_cluster_size.stdout
  when: wsrep_cluster_size.stdout is defined

- name: Set wsrep_cluster_size error (if there is an error)
  set_fact:
    galera_errors: true
    infrastructure_errors: true
    wsrep_cluster_size_error: true
  when: "'{{ groups['galera_all']|length }}' not in wsrep_cluster_size.stdout or wsrep_cluster_size.rc != 0"

- name: Display wsrep_cluster_size_error
  debug:
    var: wsrep_cluster_size_error
  when: wsrep_cluster_size_error is defined

- name: Confirm wsrep_cluster_status
  shell: "mysql -e \"show status like 'wsrep_cluster_status'\" | grep wsrep_cluster_status | awk '{print $2}'"
  register: wsrep_cluster_status
  delegate_to: "{{ groups['galera_all'][0] }}"
  ignore_errors: yes

- name: Display wsrep_cluster_status
  debug:
    var: wsrep_cluster_status.stdout
  when: wsrep_cluster_status.stdout is defined

- name: Set wsrep_cluster_status error (if there is an error)
  set_fact:
    galera_errors: true
    infrastructure_errors: true
    wsrep_cluster_status_error: true
  when: "'Primary' not in wsrep_cluster_status.stdout or wsrep_cluster_status.rc != 0"

- name: Display wsrep_cluster_status_error
  debug:
    var: wsrep_cluster_status_error
  when: wsrep_cluster_status_error is defined
