---
# Copyright 2018, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Galera QC
- include: galera.yml

# RabbitMQ QC
- include: rabbitmq.yml

# Create the Infrastructure QC Log Directory
- name: Create Infrastructure QC Log Directory
  file:
    path: "{{ infra_qc_dir }}"
    state: directory
    mode: 0755
    recurse: yes

# Output Infrastructure QC into log file
- name: Output Infrastructure QC into log file
  template:
    src: "infrastructure.txt.j2"
    dest: "{{ infra_qc_dir }}/infrastructure-qc-{{ datetime_stamp }}.txt"

# Output Infrastructure Errors into error log file
- name: Output Infrastructure Errors into log file
  template:
    src: "infrastructure_erros.err.j2"
    dest: "{{ infra_qc_dir }}/infrastructure-errors-{{ datetime_stamp }}.err"
  when: infrastructure_error is defined
