---
# Copyright 2018, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Grab full output of rabbitmqctl cluster_status
  command: "rabbitmqctl cluster_status"
  register: rabbitmqctl_output
  delegate_to: "{{ groups['rabbitmq'][0] }}"
  ignore_errors: yes

- name: Display output of rabbitmqctl cluster_status
  debug:
    var: rabbitmqctl_output.stdout_lines
  when: rabbitmqctl_output.stdout_lines is defined

- name: Set rabbitmqctl_rc error (if needed)
  set_fact:
    rabbitmq_errors: true
    infrastructure_errors: true
    rabbitmqctl_rc_error: true
  when: rabbitmqctl_output.rc != 0

- name: Display rabbitmqctl_rc
  debug:
    var: rabbitmqctl_rc_error
  when: rabbitmqctl_rc_error is defined

- name: Set rabbitmq_parition error (if needed)
  set_fact:
    rabbitmq_errors: true
    infrastructure_errors: true
    rabbitmq_partition_error: true
  when: "'{partitions,[]}' not in rabbitmqctl_output.stdout or rabbitmqctl_output.rc != 0"

- name: Display rabbitmq_partition_error
  debug:
    var: rabbitmq_partition_error
  when: rabbitmq_partition_error is defined
