---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

pre_upgrade_original_playbook_dir: "/opt/rpc-openstack/"

date_stamp: "{{ ansible_date_time.date }}"
time_stamp: "{{ ansible_date_time.time |replace(':','')}}"
datetime_stamp: "{{ date_stamp }}-{{ time_stamp }}"
local_home: "{{ lookup('env', 'HOME') }}"

marker_dir: "{{ ansible_env.UPGRADE_LEAP_MARKER_FOLDER | default('/etc/openstack_deploy/upgrade-leap') }}"
