#!/usr/bin/env bash
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -xeuo pipefail

echo "Gate job started"
echo "Running check/pre hook"
echo "+-------------------- START ENV VARS --------------------+"
env
echo "+-------------------- START ENV VARS --------------------+"

# If the current folder's basename is rpc-upgrades then we assume
# that it is the root of the git clone. If the git clone is not in
# /opt then we symlink the current folder there so that all the
# rpc-upgrades scripts work as expected.
if [[ "$(basename ${PWD})" == "rpc-upgrades" ]]; then
  if [[ "${PWD}" != "/opt/rpc-upgrades" ]]; then
    ln -sfn ${PWD} /opt/rpc-upgrades
  fi
fi

# Install required packages for Ubuntu 16.04
#   curl        - for getting get-pip.py
#   iptables    - OSA gate-check-commit script expects it on the host
#   python      - for installing pip using get-pip.py
#   python-yaml - for ansible and reading yaml files (like the rpc release info)
#   util-linux  - for the 'lsblk' tool used by OSA gate-check-commit script
#   wget        - TODO: provide reason for wget's inclusion here

if which apt-get; then
    sudo apt-get update
    sudo apt-get install -y curl iptables python python-yaml util-linux wget
fi

# Install required packages for CentOS 7
#   curl            - for getting get-pip.py
#   epel-release    - required to install python-ndg_httpsclient/python2-pyasn1
#   python          - for installing pip using get-pip.py
#   redhat-lsb-core - for bindep profile support
#   wget            - TODO: provide reason for wget's inclusion here
if which yum; then
    sudo yum install -y curl epel-release python redhat-lsb-core wget
fi

# Download the get-pip script using the primary or secondary URL
GETPIP_CMD="curl --silent --show-error --retry 5"
GETPIP_FILE="/tmp/get-pip.py"
GETPIP_PYTHON_EXEC_PATH="$(which python2.7)"
${GETPIP_CMD} https://bootstrap.pypa.io/get-pip.py > ${GETPIP_FILE}\
    || ${GETPIP_CMD} https://raw.githubusercontent.com/pypa/get-pip/master/get-pip.py > ${GETPIP_FILE}

# Install specific verison of pip/setuptools/wheel.
sudo ${GETPIP_PYTHON_EXEC_PATH} ${GETPIP_FILE} 'pip==9.0.3' 'setuptools==39.0.1' 'wheel==0.30.0'

# Install bindep and tox with pip.
sudo pip install bindep tox
