#!/bin/bash

## Shell Opts ----------------------------------------------------------------

set -eux
set -o pipefail

source "$(readlink -f $(dirname ${0}))/../gating_vars.sh"

## Main ----------------------------------------------------------------------

# If the current folder's basename is rpc-upgrades then we assume
# that it is the root of the git clone. If the git clone is not in
# /opt then we symlink the current folder there so that all the
# rpc-upgrades scripts work as expected.
if [[ "$(basename ${PWD})" == "rpc-upgrades" ]]; then
  if [[ "${PWD}" != "/opt/rpc-upgrades" ]]; then
    ln -sfn ${PWD} /opt/rpc-upgrades
  fi
fi

# We need to ensure that we use the rackspace mirrors, as they are
# most reliable. We also need to ensure that python and the python
# yaml library are present for ansible to work.
source "$(readlink -f $(dirname ${0}))/../gating_prerequisites.sh"

echo "Gate job started"
echo "Running check/pre hook"
echo "+-------------------- START ENV VARS --------------------+"
env
echo "+-------------------- START ENV VARS --------------------+"

# Download the get-pip script using the primary or secondary URL
GETPIP_CMD="curl --silent --show-error --retry 5"
GETPIP_FILE="/tmp/get-pip.py"
GETPIP_PYTHON_EXEC_PATH="$(which python2.7)"
${GETPIP_CMD} https://bootstrap.pypa.io/3.3/get-pip.py > ${GETPIP_FILE}\
    || ${GETPIP_CMD} https://raw.githubusercontent.com/pypa/get-pip/master/3.3/get-pip.py > ${GETPIP_FILE}

# Install specific verison of pip/setuptools/wheel.
# virtualenv >= 20 seems to trigger https://github.com/pypa/virtualenv/issues/1638
sudo ${GETPIP_PYTHON_EXEC_PATH} ${GETPIP_FILE} 'pip==9.0.3' 'setuptools==39.0.1' 'wheel==0.30.0' 'virtualenv<20'

# Install bindep and tox with pip.
sudo pip install bindep tox
