---
# Copyright 2018, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather Openstack CLI Version
  shell: "source ~/openrc; openstack --version 2>&1"
  args:
    executable: /bin/bash
  register: openstack_cli_version
  delegate_to: "{{ groups['utility'][0] }}"

- name: Output Openstack CLI Version
  debug:
    var: openstack_cli_version.stdout

- name: Gather Cinder CLI Version
  shell: "source ~/openrc; cinder --version 2>&1"
  args:
    executable: /bin/bash
  register: cinder_cli_version
  delegate_to: "{{ groups['utility'][0] }}"

- name: Output Cinder CLI Version
  debug:
    var: cinder_cli_version.stdout

- name: Gather Glance CLI Version
  shell: "source ~/openrc; glance --version 2>&1"
  args:
    executable: /bin/bash
  register: glance_cli_version
  delegate_to: "{{ groups['utility'][0] }}"

- name: Output Glance CLI Version
  debug:
    var: glance_cli_version.stdout

- name: Gather Keystone CLI Version
  shell: "source ~/openrc; keystone --version 2>&1"
  args:
    executable: /bin/bash
  register: keystone_cli_version
  delegate_to: "{{ groups['utility'][0] }}"

- name: Output Keystone CLI Version
  debug:
    var: keystone_cli_version.stdout_lines[-1]

- name: Gather Neutron CLI Version
  shell: "source ~/openrc; neutron --version 2>&1"
  args:
    executable: /bin/bash
  register: neutron_cli_version
  delegate_to: "{{ groups['utility'][0] }}"

- name: Output Neutron CLI Version
  debug:
    var: neutron_cli_version.stdout

- name: Gather Nova CLI Version
  shell: "source ~/openrc; nova --version 2>&1"
  args:
    executable: /bin/bash
  register: nova_cli_version
  delegate_to: "{{ groups['utility'][0] }}"

- name: Output Nova CLI Version
  debug:
    var: nova_cli_version.stdout

# Set orchestration result depeding on available openstack client
- name: Gather Orchestration CLI Version (openstack_cli_version >= "2.3.0")
  shell: "source ~/openrc; openstack orchestration --version 2>&1"
  args:
    executable: /bin/bash
  register: orchestration_cli_version
  when: openstack_cli_version.stdout.split('openstack')[1] >= "2.3.0"
  delegate_to: "{{ groups['utility'][0] }}"

- name: Gather heat service list (openstack_cli_version < "2.3.0")
  shell: "source ~/openrc; heat --version 2>&1"
  args:
    executable: /bin/bash
  register: orchestration_cli_version
  when: openstack_cli_version.stdout.split('openstack')[1] < "2.3.0"
  delegate_to: "{{ groups['utility'][0] }}"

- name: Output Orchestration CLI Version
  debug:
    var: orchestration_cli_version.stdout

- name: Gather Swift CLI Version
  shell: "source ~/openrc; swift --version 2>&1"
  args:
    executable: /bin/bash
  register: swift_cli_version
  ignore_errors: yes
  delegate_to: "{{ groups['utility'][0] }}"

- name: Output Swift CLI Version
  debug:
    var: swift_cli_version.stdout
  when: swift_cli_version is defined

# Need to add CEPH CLI things here (jwagner)
